hive/hive/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import queen

urlpatterns = [
    url(r'^queen/', include('queen.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',queen.views.home, name='home'),
]

hive/queen/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^write/?$', views.write, name='write'),
    url(r'^(?P<abc>[0-9]+)/$', views.detail, name='detail'),
    url(r'^collect/?$', views.collect, name='collect'),
    url(r'^send/?$', views.send, name='send'),
    url(r'^register/?$', views.register, name='register'),
]

hive/queen/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.utils.encoding import python_2_unicode_compatible
# Create your models here.
@python_2_unicode_compatible  # only if you need to support Python 2
class Abc(models.Model):
    question_text = models.CharField(max_length=200)
    def __str__(self):
        return self.question_text

@python_2_unicode_compatible  # only if you need to support Python 2
class Message(models.Model):
    #is_notification
    #expied_on
    #platform
    title = models.CharField(max_length=200)
    cotent = models.CharField(max_length=200)
    created_on = models.DateTimeField('created')
    def __str__(self):
        return self.title

@python_2_unicode_compatible  # only if you need to support Python 2
class MsgRecord(models.Model):
    msg = models.ForeignKey(Message, on_delete=models.CASCADE) 
    plaform = models.CharField(max_length=200)
    token = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    sent_on = models.DateTimeField('sent')
    reach_on = models.DateTimeField('reach')
    def __str__(self):
        return self.token

@python_2_unicode_compatible  # only if you need to support Python 2
class Token(models.Model):
    token = models.CharField(max_length=200)
    platform = models.CharField(max_length=200)
    
    def __str__(self):
        return self.token

hive/queen/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from .models import Message, MsgRecord
from django.views.decorators.csrf import csrf_exempt
from pprint import pprint
from pms import pm

# Create your views here.
def index(request):
    msg_list = Message.objects.order_by('created_on')[:5]
    context = {'msg_list': msg_list}
    return render(request, 'queen/index.html', context)

def detail(request, abc):
    try:
        msg = Message.objects.get(pk=abc)
    except Message.DoesNotExist:
        raise Http404("Message does not exist")
    return render(request, 'queen/detail.html', {'msg': msg})

def collect(request):
    return HttpResponse("123 Collect OK")

def write(request):
    return render(request, 'queen/write.html')

@csrf_exempt
def send(request):
    log = pm.push(request.POST)
    return render(request, 'queen/send.html', {'send_list': log})
    #return HttpResponse(log)

@csrf_exempt
def register(request):
    log = pm.register(request.POST)
    return HttpResponse(log)

def home(request):
	return render(request, 'queen/home.html', {})

hive/queen/templates/queen/detail.html
<h1>{{ msg.title }}:{{ msg.content }}</h1>
<ul>
{% for record in msg.msgrecord_set.all %}
    <li>{{record.plaform}},{{record.token}},{{record.phone}},{{record.sent_on}}</li>
{% endfor %}
</ul>

hive/queen/templates/queen/home.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>a</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container-fluid">
        
            <div class="col-md-4 col-xs-2">
            </div>
            <div class="col-md-4 col-xs-8">
                <h1>Home</h1>
                <p class="lead" >https://fir.im/sack</p>
                <p>
                    <a class="btn btn-primary btn-large" href="https://fir.im/sack">Download Push Collector</a>
                </p>
            </div>
            <div class="col-md-4 col-xs-2">
            </div>
        
    </div>
</body>

</html>

hive/queen/templates/queen/index.html
{% if msg_list %}
    <ul>
    {% for msg in msg_list %}
        <li><a href="{% url 'detail' msg.id %}/">{{ msg.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

hive/queen/templates/queen/send.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Result</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-3 column">
            </div>
            <div class="col-md-6 column">
                <h2>
                Result
            </h2>
                <p>
                    用于测试发布Push Message. 将生成Message，然后推送到各个Push Server.
                </p>
                {% for send in send_list %}
                    {% if send.status < 1 %}
                        <div class="panel panel-success">
                        <div class="panel-heading">
                        <h3 class="panel-title">Success {{send.title}}</h3>
                    </div>
                    {% else %}
                        <div class="panel panel-danger">
                        <div class="panel-heading">
                        <h3 class="panel-title">Fail {{send.title}}</h3>
                    </div>
                    {% endif %}
                
                    
                    <div class="panel-body">
                        {{send.message}}
                    </div>
                </div>
                
                {% endfor %}
                
            </div>
            <div class="col-md-3 column">
            </div>
        </div>
    </div>
</body>

</html>

hive/queen/templates/queen/write.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>send Message</title>
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-3 column">
            </div>
            <div class="col-md-6 column">
                <h2>
                Send Push Message
            </h2>
                <p>
                    用于测试发布Push Message. 将生成Message，然后推送到各个Push Server.
                </p>
                <form role="form" action="{% url 'send' %}" method="post" target="_blank">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">Title:</span>
                            <input type="text" class="form-control" placeholder="请输入标题" aria-describedby="basic-addon1" id="title" name="title">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">Body:</span>
                            <input type="text" class="form-control" placeholder="请输入内容" aria-describedby="basic-addon1" id="content" name="content">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">Extra:</span>
                            <input type="text" class="form-control" placeholder="请输入自定义信息" aria-describedby="basic-addon1" id="extra" name="extra">
                        </div>
                        <p class="help-block">输入自定义信息，用于透传消息</p>
                    </div>
                    <div class="form-group">
                        <label for="content">选择消息类型</label>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="notification" /> Notification
                            </label>
                            <label>
                                <input type="checkbox" name="payload" /> Payload
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="content">选择第三方平台</label>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="mi"> 小米
                            </label>
                            <label>
                                <input type="checkbox" name="huawei"> 华为
                            </label>
                            <label>
                                <input type="checkbox" name="getui"> 个推
                            </label>
                            <label>
                                <input type="checkbox" name="umeng"> 友盟
                            </label>

                            <label>
                                <input type="checkbox" name="tt"> 腾讯信鸽
                            </label>
                            <label>
                                <input type="checkbox" name="baidu"> 百度
                            </label>
                            <label>
                                <input type="checkbox" name="ali"> 阿里云
                            </label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary" value="Vote"> 发 送 </button>
                </form>
            </div>
            <div class="col-md-3 column">
            </div>
        </div>
    </div>
</body>

</html>